SERMON_LETTERBOX_VIDEO_AREA_POSITION_Y = 0.30
SERMON_LETTERBOX_TITLE_POSITION_Y = 0.08
SERMON_LETTERBOX_SUBTITLE_POSITION_Y = 0.21
SERMON_LETTERBOX_BANNER_WIDTH_RATIO = 0.46
SERMON_LETTERBOX_BANNER_POSITION_X = 0.5
SERMON_LETTERBOX_BANNER_POSITION_Y = 0.83
