SERMON_LETTERBOX_ZOOM_SCALE = 1.30
SERMON_LETTERBOX_CROP_POSITION_X = 0.50
SERMON_LETTERBOX_CROP_POSITION_Y = 0.42
SERMON_LETTERBOX_VIDEO_AREA_POSITION_Y = 0.28
SERMON_LETTERBOX_VIDEO_AREA_POSITION_MIN = 0.22
SERMON_LETTERBOX_VIDEO_AREA_POSITION_MAX = 0.34
SERMON_LETTERBOX_PLAYBACK_RATE = 1.20
SERMON_LETTERBOX_TITLE_FONT_SCALE = 1.20
SERMON_LETTERBOX_TITLE_POSITION_Y = 0.08
SERMON_LETTERBOX_SUBTITLE_FONT_SCALE = 1.00
SERMON_LETTERBOX_SUBTITLE_POSITION_Y = 0.24
SERMON_LETTERBOX_BANNER_WIDTH_RATIO = 0.46
SERMON_LETTERBOX_BANNER_POSITION_X = 0.5
SERMON_LETTERBOX_BANNER_POSITION_Y = 0.83

# Missing columns on legacy databases keep the historical meaning. These are
# intentionally separate from defaults for newly created drafts.
LEGACY_VIDEO_AREA_POSITION_Y = 0.30
LEGACY_SUBTITLE_POSITION_Y = 0.21
